services:
  master-pg:
    image: postgres:16
    container_name: master-pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
      - ./master-init:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=10
      -c max_replication_slots=10
    networks:
      - pg-net

  slave-pg:
    image: postgres:16
    container_name: slave-pg
    restart: always
    depends_on:
      - master-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - slave_data:/var/lib/postgresql/data
      - ./slave-init:/docker-entrypoint-initdb.d
    networks:
      - pg-net

  logs-pg:
    image: postgres:16
    container_name: logs-pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5434:5432"
    volumes:
      - logs_data:/var/lib/postgresql/data
      - ./logs-init:/docker-entrypoint-initdb.d
    networks:
      - pg-net

  classes-pg:
    image: postgres:16
    container_name: classes-pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5435:5432"
    volumes:
      - classes_data:/var/lib/postgresql/data
      - ./classes-init:/docker-entrypoint-initdb.d
    networks:
      - pg-net
  
  inventory-pg:
    image: postgres:16
    container_name: inventory-pg
    ports:
      - "5436:5432"
    networks:
      - pg-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
      TZ: Europe/Paris
    volumes:
      - inventory_data:/var/lib/postgresql/data
      - ./inventory-init:/docker-entrypoint-initdb.d

  hero-pg:
    image: postgres:16
    container_name: hero-pg
    ports:
      - "5437:5432"
    networks:
      - pg-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
      TZ: Europe/Paris
    volumes:
      - hero_data:/var/lib/postgresql/data
      - ./hero-init:/docker-entrypoint-initdb.d

  mob-redis:
    image: redis:7.2-alpine
    container_name: mob-redis
    ports:
      - "6380:6379"
    networks:
      - pg-net
    environment:
      - TZ=Europe/Paris
    volumes:
      - mob_data:/data
    command: redis-server --save 60 1 --requirepass mob-redis-dev
    
  init-mob-data:
    image: redis:7.2-alpine
    container_name: init-mob-data
    networks:
      - pg-net
    depends_on:
      - mob-redis
    volumes:
      - ./mob-init:/init-data
    entrypoint: ["sh", "-c", "sleep 5 && cat /init-data/mobs.txt | redis-cli -h mob-redis -a mob-redis-dev --pipe"]

  map-redis:
    image: redis:7.2-alpine
    container_name: map-redis
    ports:
      - "6381:6379"
    networks:
      - pg-net
    environment:
      - TZ=Europe/Paris
    volumes:
      - map_data:/data
    command: redis-server --save 60 1 --requirepass redis-qual-dev

  init-map-data: 
    image: redis:7.2-alpine
    container_name: init-map-data
    networks:
      - pg-net
    depends_on:
      - map-redis
    volumes:
      - ./map-init:/init-data:ro
    entrypoint: ["sh", "-c", "sleep 5 && cat /init-data/maps.txt | redis-cli -h map-redis -a redis-qual-dev --pipe"]

  save-redis:
    image: redis:7.2-alpine
    container_name: save-redis
    ports:
      - "6382:6379"
    networks:
      - pg-net
    environment:
      - TZ=Europe/Paris
    volumes:
      - save_data:/data
    command: redis-server --save 60 1 --requirepass redis-qual-dev

  init-save-data:
    image: redis:7.2-alpine
    container_name: init-save-data
    networks:
      - pg-net
    depends_on:
      - save-redis
    volumes:
      - ./save-init:/init-data:ro
    entrypoint: ["sh", "-c", "sleep 5 && cat /init-data/saves.txt | redis-cli -h save-redis -a redis-qual-dev --pipe"]
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg-net

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: microservice
      RABBITMQ_DEFAULT_PASS: microservice
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pg-net

networks:
  pg-net:

volumes:
  master_data:
  slave_data:
  logs_data:
  classes_data:
  map_data:
  mob_data:
  inventory_data:
  hero_data:
  save_data:
